### ISSUE TITLE
Sub classing other html elements (HTMLButtonElement)

### ISSUE THREAD

**Issue by internettrans** [github/babel-plugin-transform-custom-element-classes#1]
First off, thanks for your good work on this project - I was about to revert to es5 since Babel's default implementation  doesn't work, but then I found this project and it works great!

I am curious if you've been able to pull off sub classing  HTMLButtonElement (or any other element class besides HTMLElement). The code in this project ignores those classes - in my own testing it seems like chrome and Firefox both throw `TypeError: Illegal constructor` even if you use native classes instead of the babel compiled version.

Have you come across this? Any suggested workarounds? If so I'd be happy to help getting that into this babel plugin.

**Comment by josh** [comment]
Subclassing other builtins is pretty much on hold for now.

Even though `is=""` is technically part of the v1 spec, Apple refuses to implement it. https://github.com/w3c/webcomponents/issues/509

Totally willing to reconsider support here if all the politics are sorted out.

Thanks!
