### ISSUE TITLE
Possible to use with MediaSource?

### ISSUE THREAD

**Issue by bradisbell** [github/babel-plugin-transform-custom-element-classes#10]
When I extend MediaSource, I receive the error:

> Uncaught TypeError: Failed to construct 'MediaSource': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

This seems to be a similar problem that your library addresses for other classes.  Can the same or similar workaround be applied to MediaSource?

**Comment by josh** [comment]
I'm not sure, but the scope of this plugin targets the Custom Elements use case. Sorry.
