### ISSUE TITLE
 Reflect.construct 

### ISSUE THREAD

**Issue by puppetmaster3** [github/babel-plugin-transform-custom-element-classes#8]
Where may I find  Reflect.construct  poly fill?

**Comment by josh** [comment]
https://github.com/WebReflection/classtrophobic-es5/ is one option. You can also try https://github.com/google/closure-compiler/blob/2725a4f3b73d1536a9795424ae56bea07c949dd3/src/com/google/javascript/jscomp/js/es6/util/construct.js.
