### ISSUE TITLE
Block-scoped declarations syntax error

### ISSUE THREAD

**Issue by bgoerdt** [github/babel-plugin-transform-custom-element-classes#9]
I have a simple custom element class that I am trying to transform with this plugin:

```
var owningDocument = document.currentScript.ownerDocument;
window.addEventListener('HTMLImportsLoaded', function(e) {
    class MyCustomElement extends HTMLElement {...
    }
    window.customElements.define('my-custom-element', MyCustomElement);
});
```

But I am getting a syntax error when using the plugin:
```
events.js:154
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```

Here is my .babelrc file:
```
{
    "plugins": [
        "transform-custom-element-classes",
        "transform-es2015-classes"
    ]
}
```

Any ideas why this is happening?

**Comment by bgoerdt** [comment]
The error is happening because there is no 'use strict' at the top of the index.js file. There are already some pull requests to address this, one of them just needs to be merged.

**Comment by AndyOGo** [comment]
Both PRs #4 and #7 would fix that same issue for us.

@josh May I asked you to merge?

**Comment by AndyOGo** [comment]
I dogged deeper, the following lines are causing this bug:
https://github.com/github/babel-plugin-transform-custom-element-classes/blob/master/lib/index.js#L12-L19

**Comment by josh** [comment]
If this issue is related to an old version of node--sorry but it won't be supported.
